# CCTV News Archive - Cloudflare Pages Deployment

name: Deploy to Cloudflare Pages

on:
  schedule:
    # Run twice daily at 8 AM and 8 PM Beijing time (UTC+8)
    - cron: '0 0,12 * * *'  # 8 AM and 8 PM Beijing time
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Fetch latest news data
      run: |
        echo "Fetching latest CCTV news data..."
        node index.js
        
    - name: Build static site
      run: |
        echo "Building static website..."
        node build.js
        
    - name: Verify build output
      run: |
        echo "Checking build output..."
        ls -la dist/
        echo "Total files generated:"
        find dist/ -type f | wc -l
        
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: cctv-news-archive
        directory: dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit updated data (if any)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/
        if git diff --staged --quiet; then
          echo "No new data to commit"
        else
          git commit -m "📰 Auto-update: $(date +'%Y-%m-%d %H:%M') Beijing time [skip ci]"
          git push
        fi